---
name: Catalyst-Plugin-AuthenCookie
version: 0.05
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Plugin for cookie-based authentication
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Catalyst::Test: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  Test::More: 0
requires:
  Class::Accessor::Fast: 0
  Digest::SHA: 0
  Params::Validate: 0
configure_requires:
  Module::Build: 0.35
provides:
  Catalyst::Plugin::AuthenCookie:
    file: lib/Catalyst/Plugin/AuthenCookie.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
