---
name: Catalyst-Plugin-AuthenCookie
version: 0.01
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Plugin for cookie-based authentication
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::SHA: 0
  Params::Validate: 0
build_requires:
  Catalyst::Test: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  Test::More: 0
provides:
  Catalyst::Plugin::AuthenCookie:
    file: lib/Catalyst/Plugin/AuthenCookie.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
